var searchData=
[
  ['test_5factive_5flearner_476',['test_active_learner',['../namespacetest__active__learner.html',1,'']]],
  ['test_5ffake_5ffunction_477',['test_fake_function',['../namespacetest__fake__function.html',1,'']]],
  ['test_5fgp_478',['test_GP',['../namespacetest__GP.html',1,'']]],
  ['test_5fgp_5fkernel_479',['test_gp_kernel',['../namespacetest__gp__kernel.html',1,'']]],
  ['test_5fgv_5fucb_5flearner_480',['test_GV_UCB_learner',['../namespacetest__GV__UCB__learner.html',1,'']]],
  ['test_5fhuman_5fchoice_481',['test_human_choice',['../namespacetest__human__choice.html',1,'']]],
  ['test_5fmcmc_5fsampling_482',['test_mcmc_sampling',['../namespacetest__mcmc__sampling.html',1,'']]],
  ['test_5fmodel_483',['test_model',['../namespacetest__model.html',1,'']]],
  ['test_5fmutual_5finfo_5flearner_484',['test_mutual_info_learner',['../namespacetest__mutual__info__learner.html',1,'']]],
  ['test_5fpareto_485',['test_pareto',['../namespacetest__pareto.html',1,'']]],
  ['test_5fpreference_5fgp_486',['test_preference_GP',['../namespacetest__preference__GP.html',1,'']]],
  ['test_5fpreference_5flinear_487',['test_preference_linear',['../namespacetest__preference__linear.html',1,'']]],
  ['test_5fpreference_5fmodel_488',['test_preference_model',['../namespacetest__preference__model.html',1,'']]],
  ['test_5fpreference_5fpair_489',['test_preference_pair',['../namespacetest__preference__pair.html',1,'']]],
  ['test_5fprobits_490',['test_probits',['../namespacetest__probits.html',1,'']]],
  ['test_5frandom_5flearner_491',['test_random_learner',['../namespacetest__random__learner.html',1,'']]],
  ['test_5fucb_5flearner_492',['test_UCB_learner',['../namespacetest__UCB__learner.html',1,'']]]
];
